/* ============================================
   Expertise / Hero — ported from `mockup/expertise.html`
   --------------------------------------------
   Reduced bottom padding (the accordion follows immediately): eyebrow →
   headline with the red gradient close → lede → the dashed "Tap any area to
   expand" helper. The mockup's `data-hero` elements stagger in on load via
   `useHeroIntro`, and carry the same attribute here.

   The backdrop under a white overlay is a deliberate departure from the
   mockup, whose hero here is type-only. It is the same treatment the home
   hero settled on: the WHOLE photograph, uncropped, drawn at the largest
   size that fits inside the section, under white that holds only where the
   copy is and lets go everywhere else.

   **One framing at every device, and no crop anywhere in it.**
   `width`/`height` `auto` with `max-width`/`max-height` at 100% is the
   replaced-element algorithm, so the browser scales the frame down
   preserving its ratio and cannot crop, letterbox or stretch it. The file is
   1.63:1 against a hero that runs 545-725px tall, so up to about 1030px of
   viewport the width binds and the frame spans the section as a band across
   the top; past that the height binds, the frame goes narrower than the
   section, and being pinned `top: 0 / right: 0` it fills the hero's full
   height on the right while the copy column keeps the paper on the left.

   Its two edges that end inside the page — left and bottom — are feathered
   to nothing on a smootherstep-cubed curve; its top is the top of the page
   and its right is the hero's own, so neither needs anything.

   Over it, one white layer, and it is the thinnest one the copy allows: a
   band that starts where the copy starts below 920px, a flat 0.85 shelf that
   ends where the glyphs end above it. See the annotated `.bg` / `.scrim`
   blocks in the stylesheet for the contrast table that prices it.
   ============================================ */

import React from 'react';
import { useHeroIntro } from '../../../animations';
import layout from '../../../styles/layout.module.css';
import styles from './HeroSection.module.css';

// Self-hosted backdrop — generated by `npm run generate:images` from the
// client's `iStock1559948366-mirrored` master on Cloudinary. That master is
// 2211x1356 (1.63:1) and ships uncropped, so the large variant is 1920x1178
// and the small one 960x589.
//
// `sizes="100vw"` overstates what the hero actually draws in the
// height-limited regime (1182 CSS px at a 1920px viewport), which is the safe
// direction: it only ever picks a candidate at least as wide as the section,
// so the intrinsic width never becomes the binding term in the sizing rule
// and the frame never upscales.
const HERO_BG = '/images/hero-expertise.jpg';
const HERO_BG_SRCSET =
  '/images/hero-expertise-960.webp 960w, /images/hero-expertise-1920.webp 1920w';

const HeroSection = () => {
  const heroRef = useHeroIntro();

  return (
    <section className={styles.hero}>
      {/* Above the fold on this route — eager, and high priority so it wins
          the bandwidth race against the route chunk. `display: contents` on
          the <picture> keeps the absolutely positioned <img> laid out exactly
          as it would be as a direct child.

          A real <img> rather than a CSS background, and that is load-bearing
          rather than a preference: the element IS the drawn photograph, with
          no box fitted around it, which is what lets the stylesheet's edge
          feather be expressed in percentages of the image and land on its
          real edges. It also earns `fetchpriority="high"`, which a background
          cannot carry.

          No `useParallax`, unlike this hero before and unlike the Who We
          Serve one. Scrub parallax needs the photo drawn taller than its box
          so the travel never exposes an edge, and drawing the whole frame is
          the one thing that will not do. The backdrop is static on purpose —
          the same call the home hero makes. */}
      <picture className={styles.bgPicture}>
        <source type="image/webp" srcSet={HERO_BG_SRCSET} sizes="100vw" />
        <img
          className={styles.bg}
          src={HERO_BG}
          alt=""
          aria-hidden="true"
          width="1920"
          height="1178"
          fetchpriority="high"
          decoding="async"
        />
      </picture>
      <div className={styles.scrim} aria-hidden="true" />

      <div ref={heroRef} className={`${layout.container} ${styles.inner}`}>
        <p className="eyebrow" data-hero>
          Our expertise
        </p>

        {/* Closes on the word, not on a mark — see the home hero's "impact". */}
        <h1 className={`display display--sm ${styles.head}`} data-hero>
          Experience that connects{' '}
          <em className={`grad-text ${styles.accent}`}>
            people, processes &amp; performance
          </em>
        </h1>

        <p className={`lede ${styles.lede}`} data-hero>
          Ten connected areas of experience — the perspective organizations
          value when building stronger foundations, improving performance, and
          moving forward with confidence.
        </p>

        <p className={styles.helper} data-hero>
          <span aria-hidden="true" className={styles.dash} />
          Tap any area to expand
        </p>
      </div>
    </section>
  );
};

export default HeroSection;
