/* ============================================
   Expertise / Hero — ported from `mockup/expertise.html`
   --------------------------------------------
   Reduced bottom padding (the accordion follows immediately): eyebrow →
   headline with the red gradient close → lede → the dashed "Tap any area to
   expand" helper. The mockup's `data-hero` elements stagger in on load via
   `useHeroIntro`, and carry the same attribute here.

   The parallaxed backdrop under a double white scrim is a deliberate
   departure from the mockup, whose hero here is type-only. It is the same
   treatment the home hero uses — left-heavy white that clears toward the
   right, so the photo reads as a subject emerging from the page rather than
   as an even tint — applied to a photo with a matching composition: the
   figure sits left, the laptop and the floating record cards centre-right.
   See the annotated `.bg` / `.scrim` blocks in the stylesheet.
   ============================================ */

import React from 'react';
import { useHeroIntro, useParallax, parallaxPreset } from '../../../animations';
import layout from '../../../styles/layout.module.css';
import styles from './HeroSection.module.css';

// Self-hosted backdrop — generated by `npm run generate:images`. The master is
// 1.63:1 and ships uncropped, so the large variant is 1920x1178.
const HERO_BG = '/images/hero-expertise.jpg';
const HERO_BG_SRCSET =
  '/images/hero-expertise-960.webp 960w, /images/hero-expertise-1920.webp 1920w';

const HeroSection = () => {
  const heroRef = useHeroIntro();
  const bgRef = useParallax(parallaxPreset(-16));

  return (
    <section className={styles.hero}>
      {/* Above the fold on this route — eager, and high priority so it wins
          the bandwidth race against the route chunk. `display: contents` on
          the <picture> keeps the absolutely positioned <img> laid out exactly
          as it would be as a direct child. */}
      <picture className={styles.bgPicture}>
        <source type="image/webp" srcSet={HERO_BG_SRCSET} sizes="100vw" />
        <img
          ref={bgRef}
          className={styles.bg}
          src={HERO_BG}
          alt=""
          aria-hidden="true"
          width="1920"
          height="1178"
          fetchpriority="high"
          decoding="async"
        />
      </picture>
      <div className={styles.scrim} aria-hidden="true" />

      <div ref={heroRef} className={`${layout.container} ${styles.inner}`}>
        <p className="eyebrow" data-hero>
          Our expertise
        </p>

        {/* Closes on the word, not on a mark — see the home hero's "impact". */}
        <h1 className={`display display--sm ${styles.head}`} data-hero>
          Experience that connects{' '}
          <em className={`grad-text ${styles.accent}`}>
            people, processes &amp; performance
          </em>
        </h1>

        <p className={`lede ${styles.lede}`} data-hero>
          Ten connected areas of experience — the perspective organizations
          value when building stronger foundations, improving performance, and
          moving forward with confidence.
        </p>

        <p className={styles.helper} data-hero>
          <span aria-hidden="true" className={styles.dash} />
          Tap any area to expand
        </p>
      </div>
    </section>
  );
};

export default HeroSection;
