/* ============================================
   Home / Hero — ported 1:1 from `mockup/index.html`
   --------------------------------------------
   A photographic backdrop, then the badge → headline → lede → CTAs → four
   pillars, all staggered in on load by `useHeroIntro` (the mockup's
   `data-hero` elements, marked with the same attribute here).

   The backdrop photo is a deliberate departure from `mockup/index.html`, which
   uses an architectural shot here: it is a handshake framed at forearm level
   against a blown-out white window.

   **The two breakpoints frame it two different ways, and the split is at the
   920px nav breakpoint.**

   From 920px up the WHOLE photograph is drawn, uncropped, at the largest size
   that fits inside the section — `width`/`height` `auto` with `max-width` and
   `max-height` at 100%, which is the replaced-element algorithm and so cannot
   crop, letterbox or stretch it. The file is 2.63:1 against a hero that runs
   1.43:1 at 1440px, so on every ordinary desktop the width binds and the frame
   lands as a band across the TOP of the section: 543px of a 1002px hero at
   1440px. Because it spans the section, image-x maps straight onto hero-x, so
   the joined hands (55.4%-85.7% of the file, skin centroid 68.1%) sit at those
   same fractions of the hero — the clasp at 68%, just right of where the red
   accent word "impact" ends — with no framing constant left to tune. Its top
   edge is the top of the page and its sides are the viewport's, so the one
   edge that exists inside the section is the bottom, and that one is feathered
   to nothing.

   Below 920px the copy spans the full width, so the frame is drawn WHOLE
   instead, at a stated width, pinned to the top of the section and bled off
   both sides: `width: var(--bg-w); height: auto` on a 2.63:1 file is the
   entire sizing rule. Its bottom edge ends inside the section and is feathered
   to nothing so it dissolves rather than cuts; the left and right run off the
   page, and the top sits under the fixed 68px header. That feather is an eased
   curve — smootherstep cubed — sampled at twentieths, and both of those
   matter: a CSS gradient is piecewise-linear between its stops, so what reads
   as a line in a soft ramp is not its steepness but any place its SLOPE
   changes.

   Over it sits a white overlay, and it too splits at 920px.

   On desktop it is one horizontal layer: a shelf and a plunge. The white holds
   across the copy column — 0.86 at the left edge, 0.84 at 30%, 0.83 where the
   glyphs end — then drops to 0.08 inside the next 8% of the hero and to
   nothing 8% after that, so the copy sits on paper and the clasp on clear
   photograph. The shelf is where nearly all of the photograph lives, which is
   why its alpha is the number the section is actually tuned on. The first two
   stops come down five and four points from the shelf this replaces; the third
   cannot move, because it is what prices the red accent on "impact" — the one
   run of copy that is colour-bound rather than ink-black — which measures
   3.11:1 at its worst width against a 3:1 floor for large text.

   Below the breakpoint the copy spans the frame, so a vertical veil takes over
   legibility and the fade is left to do nothing but keep the left edge clean.
   See the annotated `.bg` and `.scrim` blocks in the stylesheet.
   ============================================ */

import React from 'react';
import { Link } from 'react-router-dom';
import { useModal } from '../../../context/ModalContext';
import { siteConfig } from '../../../data/siteConfig';
import { useHeroIntro } from '../../../animations';
import layout from '../../../styles/layout.module.css';
import styles from './HeroSection.module.css';

// Self-hosted backdrop — generated by `npm run generate:images`. Preloaded in
// `public/index.html`, so the two must be kept in sync.
//
// `-v6` supersedes the `hero-home-v5` files rather than replacing them in
// place: `/images/**` answers `immutable` for a year (see `public/.htaccess`),
// so a same-name swap would leave every returning visitor on the old photo. It
// is the 5000x1900 (2.63:1) client master that once shipped as `hero-home-v4`,
// back again — but under a third basename for that same caching reason, not
// revived under the old one.
//
// One width, and no `sizes`: from 920px up the photograph is drawn whole, at
// the largest box that fits the section, which its own intrinsic width caps at
// 2880 CSS px; below it the frame is drawn at exactly `--bg-w`, which caps at
// 1400 CSS px. Neither ever asks the file for more pixels than it has — the
// desktop cap IS the file — and the shallow depth of field keeps it at 39 KB.
//
// **The WebP is the only variant the hero paints.** There is no `<picture>` and
// no `image-set()` fallback, which costs less than it sounds: an `<img src>` on
// a WebP is supported back to Safari 14 and Chrome 32, a WIDER floor than
// `image-set()` with `type()` (Safari 17, Chrome 113) would have given. Older
// engines than that get no backdrop, which the section survives intact — the
// image is decorative and `aria-hidden`, the overlay above it is white, and
// every glyph in the hero is specified against white first.
//
// `public/images/hero-home-v6.jpg` is still emitted next to it — every photo in
// `generate-images` gets a universal JPEG fallback — and is simply not
// referenced from anywhere; it is the file a `<picture>` here would need.
//
// `HERO_BG` is the third place this filename lives, after `generate-images` and
// the LCP preload in `public/index.html`; keep it in sync with the preload.
const HERO_BG = '/images/hero-home-v6-2880.webp';

// The intrinsic size of that file. Passed through as the `width`/`height`
// attributes so the box has an aspect ratio before the bytes land. Above 920px
// the stylesheet leaves both CSS dimensions `auto` and constrains them with
// `max-width`/`max-height`, so this pair is also where the sizing starts;
// below 920px it overrides them with `var(--bg-w)` and `height: auto`.
const HERO_BG_SIZE = { width: 2880, height: 1094 };

const PILLARS = [
  { num: '01', label: 'Business Solutions' },
  { num: '02', label: 'People & Organization' },
  { num: '03', label: 'Corporate Services' },
  { num: '04', label: 'Leadership & Capability' },
];

const HeroSection = () => {
  const { openLeadModal } = useModal();
  const heroRef = useHeroIntro();

  return (
    <section className={styles.hero}>
      {/* The backdrop and the overlay: two elements, one treatment — keep them
          grouped. `.scrim` is `inset: 0` at every width, which is what makes
          the fade's stops section percentages. The photograph never is: at
          every width it is a placed element sized to its own aspect — by the
          `--bg-*` properties below 920px, and by `max-width`/`max-height` on an
          intrinsically-sized box above it.

          It is a real `<img>` rather than a CSS background, and that stays
          load-bearing at both breakpoints. The element IS the drawn photograph,
          with no box fitted around it, which is what lets the stylesheet's edge
          feather be expressed in percentages of the image and land on its real
          edges. At every width it earns `fetchpriority="high"`, which a
          background cannot carry — this is the LCP element on the site's
          busiest route.

          The `width`/`height` attributes are the file's intrinsic size, so the
          box has an aspect ratio before the bytes land — and above 920px they
          are also what the sizing rule starts from, since both CSS dimensions
          are `auto` there.

          It stays decorative: empty `alt` plus `aria-hidden`, since the hero's
          meaning is entirely in the copy beside it.

          No `useParallax` here, unlike the Expertise and Who We Serve heroes.
          Scrub parallax needs the photo drawn taller than its box so the travel
          never exposes an edge, which is the one thing this framing will not
          do. The backdrop is static on purpose. */}
      <img
        className={styles.bg}
        src={HERO_BG}
        alt=""
        aria-hidden="true"
        width={HERO_BG_SIZE.width}
        height={HERO_BG_SIZE.height}
        fetchpriority="high"
        decoding="async"
      />
      <div className={styles.scrim} aria-hidden="true" />

      <div ref={heroRef} className={`${layout.container} ${styles.inner}`}>
        <div className={styles.badge} data-hero>
          <span className={styles.dot} aria-hidden="true" /> {siteConfig.tagline}
        </div>

        {/* Deliberate departure from `mockup/index.html`, which stops both
            clauses with a full stop. The comma carries the first line into the
            second, and the headline closes on the word "impact" itself rather
            than on a mark — at every width, since this is one string wrapped by
            a single unconditional <br />. */}
        <h1 className="display" data-hero>
          We don&rsquo;t just offer services,
          <br />
          We deliver <em className={`grad-text ${styles.impact}`}>impact</em>
        </h1>

        <p className={`lede ${styles.lede}`} data-hero>
          <b className="brand">{siteConfig.brandName}</b> works with businesses,
          institutions, entrepreneurs, and professionals to navigate complexity,
          strengthen organizational capability, and build for sustainable
          growth.
        </p>

        <div className={styles.cta} data-hero>
          <button
            type="button"
            className="btn btn--primary"
            onClick={() => openLeadModal('home-hero')}
          >
            Start a Conversation <span aria-hidden="true">&rarr;</span>
          </button>
          <Link to="/expertise" className="btn btn--outline">
            Explore Our Expertise
          </Link>
        </div>

        <div className={styles.pillars} data-hero>
          {PILLARS.map((pillar) => (
            <div key={pillar.num}>
              <b>{pillar.num}</b>
              <span>{pillar.label}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
