/* ============================================
   Home / Hero — ported 1:1 from `mockup/index.html`
   --------------------------------------------
   A full-bleed photographic backdrop, a floating Dulcey "DLS" mark, then the
   badge → headline → lede → CTAs → four pillars, all staggered in on load by
   `useHeroIntro` (the mockup's `data-hero` elements, marked with the same
   attribute here).

   The backdrop photo is a deliberate departure from `mockup/index.html`,
   which uses an architectural shot here: it is a handshake framed at forearm
   level against a blown-out white window. **The whole frame is shown at every
   viewport** — it is drawn CONTAINED rather than cropped, so no part of the
   photograph is ever cut off on any device — and its own edges are feathered to
   nothing so it dissolves into the page instead of ending on a line, the white
   left over around it being simply the page: same white, no seam.

   **The box it is contained in is not the section, and that is what sets its
   size.** `contain` fixes the frame's shape but takes its scale from whatever
   holds it, and a section-sized box draws the photograph as wide as the hero —
   1430px at 1440px, 1910px at 1920px, the clasp alone spanning 372px and 497px.
   Uncropped is not the same as unenlarged. So `.bgWrap` is a placed box
   instead: `--bg-w` wide, pinned to the hero's right edge, under the header on
   phones and centred on the hero's height from 920px up. The frame stays whole;
   it is drawn at 1058px and 1413px, with the clasp at 275px and 367px.

   Over it sits a white overlay that runs left to right, thin enough across the
   copy that the photograph reads as a photograph: from 920px up that fade alone
   carries legibility, holding 0.92 → 0.86 across the copy and letting go within
   8% of the hero after the glyphs end. Pinning the frame right moves the clasp
   from 68% of the hero to about 76%, which is inside that plunge rather than
   under the shelf — so the shelf could go back up (0.82 → 0.86) and MORE of the
   subject survives, not less. Below the breakpoint the copy spans the frame, so
   a vertical veil joins the fade; that rule is untouched, because the band now
   sits above the headline instead of behind it. See the annotated `.bgWrap` /
   `.bg` / `.scrim` blocks in the stylesheet.
   ============================================ */

import React from 'react';
import { Link } from 'react-router-dom';
import { useModal } from '../../../context/ModalContext';
import { siteConfig, MARK_SIZE } from '../../../data/siteConfig';
import { useHeroIntro } from '../../../animations';
import layout from '../../../styles/layout.module.css';
import styles from './HeroSection.module.css';

// Self-hosted backdrop — generated by `npm run generate:images`. Preloaded in
// `public/index.html`, so the two must be kept in sync.
//
// `-v6` supersedes the `hero-home-v5` files rather than replacing them in
// place: `/images/**` answers `immutable` for a year (see `public/.htaccess`),
// so a same-name swap would leave every returning visitor on the old photo. It
// is the 5000x1900 (2.63:1) client master that once shipped as `hero-home-v4`,
// back again — but under a third basename for that same caching reason, not
// revived under the old one.
//
// One width, and no `sizes`: the frame is never drawn wider than `--bg-w`,
// which caps at 1460 CSS px from 920px up and 900 CSS px below it — exactly 2x
// this file on a retina display, so it never upscales — and the shallow depth
// of field keeps it at 39 KB.
//
// **The WebP is the only variant the hero paints.** There is no `<picture>` and
// no `image-set()` fallback, which costs less than it sounds: an `<img src>` on
// a WebP is supported back to Safari 14 and Chrome 32, a WIDER floor than
// `image-set()` with `type()` (Safari 17, Chrome 113) would have given. Older
// engines than that get no backdrop, which the section survives intact — the
// image is decorative and `aria-hidden`, the overlay above it is white, and
// every glyph in the hero is specified against white first.
//
// `public/images/hero-home-v6.jpg` is still emitted next to it — every photo in
// `generate-images` gets a universal JPEG fallback — and is simply not
// referenced from anywhere; it is the file a `<picture>` here would need.
//
// `HERO_BG` is the third place this filename lives, after `generate-images` and
// the LCP preload in `public/index.html`; keep it in sync with the preload.
const HERO_BG = '/images/hero-home-v6-2880.webp';

// The intrinsic size of that file. Passed through as the `width`/`height`
// attributes so the box has an aspect ratio before the bytes land; the
// stylesheet then fits it with `max-width`/`max-height` and leaves both
// dimensions `auto`, which is what resolves it to the contain box.
const HERO_BG_SIZE = { width: 2880, height: 1094 };

const PILLARS = [
  { num: '01', label: 'Business Solutions' },
  { num: '02', label: 'People & Organization' },
  { num: '03', label: 'Corporate Services' },
  { num: '04', label: 'Leadership & Capability' },
];

const HeroSection = () => {
  const { openLeadModal } = useModal();
  const heroRef = useHeroIntro();

  return (
    <section className={styles.hero}>
      {/* The backdrop and the overlay: two boxes. Only `.scrim` is `inset: 0`,
          which is what makes the fade's stops section percentages; `.bgWrap` is
          the placed box the frame is contained in, sized and positioned by the
          `--bg-*` custom properties on `.hero`. They no longer share a geometry
          rule, but they are still one treatment — keep them grouped.

          The photograph is a real `<img>` centred in the first box, not a CSS
          background, and that is what makes "the whole frame, uncropped" work:
          at `max-width`/`max-height: 100%` with both dimensions `auto` the
          element resolves to exactly the contain box, so it IS the drawn photo
          and the stylesheet's edge feather can be expressed in percentages of
          the image itself. A background would keep the element at full section
          size with the letterbox baked in, and the feather would have nothing
          fixed to aim at. Being an `<img>` also earns `fetchpriority="high"`,
          which a background cannot carry.

          It stays decorative: empty `alt` plus `aria-hidden`, since the hero's
          meaning is entirely in the copy beside it.

          No `useParallax` here, unlike the Expertise and Who We Serve heroes.
          Scrub parallax needs the photo drawn larger than its box so the travel
          never exposes an edge — the opposite of showing the whole frame. The
          backdrop is static on purpose. */}
      <div className={styles.bgWrap} aria-hidden="true">
        <img
          className={styles.bg}
          src={HERO_BG}
          alt=""
          width={HERO_BG_SIZE.width}
          height={HERO_BG_SIZE.height}
          fetchpriority="high"
          decoding="async"
        />
      </div>
      <div className={styles.scrim} aria-hidden="true" />

      <div ref={heroRef} className={`${layout.container} ${styles.inner}`}>
        {/* Decorative floating mark — the self-hosted "DLS" initialism, drawn
            up to 430px wide and shipped at 860px so it stays crisp at 2×.
            `MARK_SIZE` reserves the 1.87:1 box; the stylesheet sets the
            rendered width and leaves the height auto. */}
        <img
          className={styles.float}
          src={siteConfig.logoMark}
          alt=""
          aria-hidden="true"
          width={MARK_SIZE.width}
          height={MARK_SIZE.height}
          decoding="async"
        />

        <div className={styles.badge} data-hero>
          <span className={styles.dot} aria-hidden="true" /> {siteConfig.tagline}
        </div>

        {/* Deliberate departure from `mockup/index.html`, which stops both
            clauses with a full stop. The comma carries the first line into the
            second, and the headline closes on the word "impact" itself rather
            than on a mark — at every width, since this is one string wrapped by
            a single unconditional <br />. */}
        <h1 className="display" data-hero>
          We don&rsquo;t just offer services,
          <br />
          We deliver <em className={`grad-text ${styles.impact}`}>impact</em>
        </h1>

        <p className={`lede ${styles.lede}`} data-hero>
          <b className="brand">{siteConfig.brandName}</b> works with businesses,
          institutions, entrepreneurs, and professionals to navigate complexity,
          strengthen organizational capability, and build for sustainable
          growth.
        </p>

        <div className={styles.cta} data-hero>
          <button
            type="button"
            className="btn btn--primary"
            onClick={() => openLeadModal('home-hero')}
          >
            Start a Conversation <span aria-hidden="true">&rarr;</span>
          </button>
          <Link to="/expertise" className="btn btn--outline">
            Explore Our Expertise
          </Link>
        </div>

        <div className={styles.pillars} data-hero>
          {PILLARS.map((pillar) => (
            <div key={pillar.num}>
              <b>{pillar.num}</b>
              <span>{pillar.label}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
