/* ============================================
   Home / Hero — ported 1:1 from `mockup/index.html`
   --------------------------------------------
   A whole-frame photographic backdrop, a floating Dulcey "DLS" mark, then the
   badge → headline → lede → CTAs → four pillars, all staggered in on load by
   `useHeroIntro` (the mockup's `data-hero` elements, marked with the same
   attribute here).

   The backdrop photo is a deliberate departure from `mockup/index.html`,
   which uses an architectural shot here: it is a handshake framed at forearm
   level, with neither head in shot. It is drawn `object-fit: contain` across
   the full width of the section, so **the entire purchased frame is on the
   page at every viewport** — nothing is ever cropped away. Below 920px it
   sits as a clear banner between the header and the copy; from 920px up it
   sits behind the copy, bottom-anchored just above the pillars rule, under a
   two-step white overlay that fades out from left to right. The scrim alphas
   depart from the mockup for the same reason. See the annotated `.bg` /
   `.scrim` blocks in the stylesheet.
   ============================================ */

import React from 'react';
import { Link } from 'react-router-dom';
import { useModal } from '../../../context/ModalContext';
import { siteConfig, MARK_SIZE } from '../../../data/siteConfig';
import { useHeroIntro } from '../../../animations';
import layout from '../../../styles/layout.module.css';
import styles from './HeroSection.module.css';

// Self-hosted backdrop (Prompt 12) — generated by `npm run generate:images`.
// Preloaded in `public/index.html`, so the two must be kept in sync.
//
// `-v4` supersedes the `hero-home-v3` files rather than replacing them in
// place: `/images/**` answers `immutable` for a year (see `public/.htaccess`),
// so a same-name swap would leave every returning visitor on the old crop.
// Same client photo, now shipped **whole** — the generator no longer trims the
// master's right edge, because `contain` shows the frame instead of cropping
// it, and ships one 2880w variant of the full 5000x1900.
//
// One width, and no `sizes`, on purpose. `contain` draws the photo at exactly
// the hero's WIDTH (the hero box never reaches the frame's 2.63:1 below a
// ~2685px viewport), so 2880w covers a 1920px viewport at 1.5x DPR and any
// phone at 3x — a `sizes` would let a phone drop to a smaller variant, but
// there is only one variant to drop to, and it is 39 KB. The preload in
// `public/index.html` names this file directly, so adding a srcset here would
// mean keeping `imagesrcset` in step with it or paying for two downloads.
const HERO_BG = '/images/hero-home-v4.jpg';
const HERO_BG_WEBP = '/images/hero-home-v4-2880.webp';

const PILLARS = [
  { num: '01', label: 'Business Solutions' },
  { num: '02', label: 'People & Organization' },
  { num: '03', label: 'Corporate Services' },
  { num: '04', label: 'Leadership & Capability' },
];

const HeroSection = () => {
  const { openLeadModal } = useModal();
  const heroRef = useHeroIntro();

  return (
    <section className={styles.hero}>
      {/* `display: contents` on the <picture> keeps the absolutely
          positioned <img> laid out exactly as it was before the wrapper.

          No `useParallax` here, unlike the Expertise and Who We Serve heroes.
          Scrub parallax needs the photo drawn larger than its box so the
          travel never exposes an edge, and "larger than its box" is exactly
          what `contain` exists to prevent: any vertical travel would push the
          frame's top or foot past `overflow: hidden` and crop the thing this
          section is here to show whole. The backdrop is static on purpose. */}
      <picture className={styles.bgPicture}>
        <source type="image/webp" srcSet={HERO_BG_WEBP} />
        <img
          className={styles.bg}
          src={HERO_BG}
          alt=""
          aria-hidden="true"
          width="5000"
          height="1900"
          fetchpriority="high"
          decoding="async"
        />
      </picture>
      <div className={styles.scrim} aria-hidden="true" />

      <div ref={heroRef} className={`${layout.container} ${styles.inner}`}>
        {/* Decorative floating mark — the self-hosted "DLS" initialism, drawn
            up to 430px wide and shipped at 860px so it stays crisp at 2×.
            `MARK_SIZE` reserves the 1.87:1 box; the stylesheet sets the
            rendered width and leaves the height auto. */}
        <img
          className={styles.float}
          src={siteConfig.logoMark}
          alt=""
          aria-hidden="true"
          width={MARK_SIZE.width}
          height={MARK_SIZE.height}
          decoding="async"
        />

        <div className={styles.badge} data-hero>
          <span className={styles.dot} aria-hidden="true" /> {siteConfig.tagline}
        </div>

        {/* Deliberate departure from `mockup/index.html`, which stops both
            clauses with a full stop. The comma carries the first line into the
            second, and the headline closes on the word "impact" itself rather
            than on a mark — at every width, since this is one string wrapped by
            a single unconditional <br />. */}
        <h1 className="display" data-hero>
          We don&rsquo;t just offer services,
          <br />
          We deliver <em className={`grad-text ${styles.impact}`}>impact</em>
        </h1>

        <p className={`lede ${styles.lede}`} data-hero>
          <b className="brand">{siteConfig.brandName}</b> works with businesses,
          institutions, entrepreneurs, and professionals to navigate complexity,
          strengthen organizational capability, and build for sustainable
          growth.
        </p>

        <div className={styles.cta} data-hero>
          <button
            type="button"
            className="btn btn--primary"
            onClick={() => openLeadModal('home-hero')}
          >
            Start a Conversation <span aria-hidden="true">&rarr;</span>
          </button>
          <Link to="/expertise" className="btn btn--outline">
            Explore Our Expertise
          </Link>
        </div>

        <div className={styles.pillars} data-hero>
          {PILLARS.map((pillar) => (
            <div key={pillar.num}>
              <b>{pillar.num}</b>
              <span>{pillar.label}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
