/* ============================================
   Who We Serve / Hero — ported from `mockup/industries.html`
   --------------------------------------------
   Eyebrow → headline with the red gradient second line → lede. The mockup's
   `data-hero` elements stagger in on load via `useHeroIntro`, and carry the
   same attribute here. Bottom padding is shorter than the default hero — the
   sector grid opens right below.

   The backdrop under a white overlay is a deliberate departure from the
   mockup, which tints its photo evenly and fades it out by 75% of the width.
   It is the treatment the home and expertise heroes settled on: the WHOLE
   photograph, uncropped, under white that holds only where the copy is and
   lets go everywhere else.

   **One framing at every device, and no crop anywhere in it.** A stated
   `width: 100%` with `height: auto` is the replaced-element algorithm, so
   the intrinsic ratio picks the height and nothing can crop, letterbox or
   stretch the frame at any width. The file is 1.875:1, so it is `W x W/1.875`
   at every viewport, and the hero runs 432-560px tall: below ~875px the frame
   is the shorter of the two and draws as a band across the top, and above
   that it is TALLER than the section and hangs below it.

   That overhang is drawn rather than clipped — 35px at 1024px, 215px at
   1440px, 469px at 1920px — which is what replaced the old contain-to-fit
   sizing. Fitting the frame inside the hero had capped it at about 1040px
   wide however wide the window got, so the picture was smallest, relative to
   the section, exactly where there was most room for it. It is the hero that
   gave way, not the picture: `overflow: hidden` is gone and the sections
   below are lifted a stacking level, so the frame passes behind the sector
   grid and dissolves there.

   Three of its four edges are feathered to nothing on a smootherstep-cubed
   curve — left, bottom, and, since `[2.31.0]`, right. Only the top is left
   alone, because it is the top of the page. The right edge is the window's
   rather than a line inside the layout, which normally needs no treatment;
   it gets one here because this file's last tenth is a near-black suit and
   dark office, and the white has finished letting go by the time it arrives,
   so it was drawing a hard-edged slab against a section that dissolves into
   paper on every other side. One flat 22%, the same at every viewport.

   Over it, one white layer, and it is the thinnest one the copy allows: a
   band that starts where the copy starts below 920px, a flat 0.75 shelf that
   ends where the glyphs end above it — extended down the overhang so the
   frame does not step at the section's bottom edge, and with both segments of
   its plunge eased so neither vertex draws a vertical band. See the annotated
   `.bg` / `.scrim` blocks in the stylesheet for the contrast table that
   prices it.
   ============================================ */

import React from "react";
import { useHeroIntro } from "../../../animations";
import layout from "../../../styles/layout.module.css";
import styles from "./HeroSection.module.css";

// Self-hosted backdrop — generated by `npm run generate:images` from the
// client's `iStock-2272021169` master on Cloudinary. That master is 2370x1264
// (1.875:1) and ships uncropped, so the large variant is 1920x1024 and the
// small one 960x512. The `-v2` basename is not cosmetic: `/images/**` answers
// `immutable`, so the retired photo's name could not be reused without
// stranding returning visitors on the old image for a year.
//
// `sizes="100vw"` is now exact rather than an overstatement — the frame IS
// the section's width. Above 1920px of viewport the 1920w candidate is the
// widest there is and gets upscaled (1.33x at 2560px); the stylesheet's
// "Resolution" note says what to regenerate if that ever needs to stop.
const HERO_BG = "/images/hero-industries-v2.jpg";
const HERO_BG_SRCSET =
  "/images/hero-industries-v2-960.webp 960w, /images/hero-industries-v2-1920.webp 1920w";

const HeroSection = () => {
  const heroRef = useHeroIntro();

  return (
    <section className={styles.hero}>
      {/* Above the fold on this route — eager, and high priority so it wins
          the bandwidth race against the route chunk. `display: contents` on
          the <picture> keeps the absolutely positioned <img> laid out exactly
          as it would be as a direct child.

          A real <img> rather than a CSS background, and that is load-bearing
          rather than a preference: the element IS the drawn photograph, with
          no box fitted around it, which is what lets the stylesheet's edge
          feather be expressed in percentages of the image and land on its
          real edges. It also earns `fetchpriority="high"`, which a background
          cannot carry.

          No `useParallax` any more. Scrub parallax needs the photo drawn
          taller than its box so the travel never exposes an edge, and drawing
          the whole frame is the one thing that will not do — the overscan
          this section used to carry WAS the crop. The backdrop is static on
          purpose, the same call the home and expertise heroes make. */}
      <picture className={styles.bgPicture}>
        <source type="image/webp" srcSet={HERO_BG_SRCSET} sizes="100vw" />
        <img
          className={styles.bg}
          src={HERO_BG}
          alt=""
          aria-hidden="true"
          width="1920"
          height="1024"
          fetchpriority="high"
          decoding="async"
        />
      </picture>
      <div className={styles.scrim} aria-hidden="true" />

      <div ref={heroRef} className={`${layout.container} ${styles.inner}`}>
        <p className="eyebrow" data-hero>
          Who we serve
        </p>

        {/* Both clauses close on the word, not on a mark — see the home hero's
            "impact". The unconditional <br /> is what separates them, so the
            two lines hold at every width without the full stops. */}
        <h1 className={`display display--md ${styles.head}`} data-hero>
          Our expertise
          <br />
          <em className={`grad-text ${styles.accent}`}>Your industry</em>
        </h1>

        <p className={`lede ${styles.lede}`} data-hero>
          Our experience and professional perspective are adaptable to different
          sectors, organizational environments, and stages of growth.
        </p>
      </div>
    </section>
  );
};

export default HeroSection;
