/* ============================================
   Who We Serve / Hero — ported from `mockup/industries.html`
   --------------------------------------------
   Parallaxed backdrop under a double white scrim, then eyebrow →
   headline with the red gradient second line → lede. The mockup's
   `data-hero` elements stagger in on load via `useHeroIntro`, and carry
   the same attribute here. Bottom padding is shorter than the default
   hero — the sector grid opens right below.

   The backdrop is the client-supplied photograph, and its scrim is a
   deliberate departure from the mockup's even left-to-right tint: it is the
   home hero's treatment — near-solid white across the left column where the
   copy lives, clearing toward the right so the photo reads as one subject
   emerging from the page. The composition suits it without re-framing, and
   suits it mirrored from the other two heroes: the hand and its dark suit
   cuff enter from the right, the glowing KPI ring sits centre-left. See the
   annotated `.bg` / `.scrim` blocks in the stylesheet.
   ============================================ */

import React from 'react';
import { useHeroIntro, useParallax, parallaxPreset } from '../../../animations';
import layout from '../../../styles/layout.module.css';
import styles from './HeroSection.module.css';

// Self-hosted backdrop — generated by `npm run generate:images`. The master is
// 1.875:1 and ships uncropped, so the large variant is 1920x1024. The `-v2`
// basename is not cosmetic: `/images/**` answers `immutable`, so the retired
// photo's name could not be reused without stranding returning visitors on the
// old image for a year.
const HERO_BG = '/images/hero-industries-v2.jpg';
const HERO_BG_SRCSET =
  '/images/hero-industries-v2-960.webp 960w, /images/hero-industries-v2-1920.webp 1920w';

const HeroSection = () => {
  const heroRef = useHeroIntro();
  const bgRef = useParallax(parallaxPreset(-16));

  return (
    <section className={styles.hero}>
      {/* Above the fold on this route — eager, and high priority so it wins
          the bandwidth race against the route chunk. `display: contents` on
          the <picture> keeps the absolutely positioned <img> laid out exactly
          as it would be as a direct child. */}
      <picture className={styles.bgPicture}>
        <source type="image/webp" srcSet={HERO_BG_SRCSET} sizes="100vw" />
        <img
          ref={bgRef}
          className={styles.bg}
          src={HERO_BG}
          alt=""
          aria-hidden="true"
          width="1920"
          height="1024"
          fetchpriority="high"
          decoding="async"
        />
      </picture>
      <div className={styles.scrim} aria-hidden="true" />

      <div ref={heroRef} className={`${layout.container} ${styles.inner}`}>
        <p className="eyebrow" data-hero>
          Who we serve
        </p>

        {/* Both clauses close on the word, not on a mark — see the home hero's
            "impact". The unconditional <br /> is what separates them, so the
            two lines hold at every width without the full stops. */}
        <h1 className={`display display--md ${styles.head}`} data-hero>
          Our expertise
          <br />
          <em className={`grad-text ${styles.accent}`}>Your industry</em>
        </h1>

        <p className={`lede ${styles.lede}`} data-hero>
          Our experience and professional perspective are adaptable to different
          sectors, organizational environments, and stages of growth.
        </p>
      </div>
    </section>
  );
};

export default HeroSection;
