/* ============================================
   Who We Serve / Hero — ported from `mockup/industries.html`
   --------------------------------------------
   Eyebrow → headline with the red gradient second line → lede. The mockup's
   `data-hero` elements stagger in on load via `useHeroIntro`, and carry the
   same attribute here. Bottom padding is shorter than the default hero — the
   sector grid opens right below.

   The backdrop under a white overlay is a deliberate departure from the
   mockup, which tints its photo evenly and fades it out by 75% of the width.
   It is the treatment the home and expertise heroes settled on: the WHOLE
   photograph, uncropped, drawn at the largest size that fits inside the
   section, under white that holds only where the copy is and lets go
   everywhere else.

   **One framing at every device, and no crop anywhere in it.**
   `width`/`height` `auto` with `max-width`/`max-height` at 100% is the
   replaced-element algorithm, so the browser scales the frame down
   preserving its ratio and cannot crop, letterbox or stretch it. The file is
   1.875:1 against a hero that runs 438-555px tall, which puts the changeover
   between the two regimes almost exactly on the 920px nav breakpoint: below
   it the width binds and the frame spans the section as a band across the
   top; from 920px up the height binds, the frame goes narrower than the
   section, and being pinned `top: 0 / right: 0` it fills the hero's full
   height on the right while the copy column keeps the paper on the left.

   Its two edges that end inside the page — left and bottom — are feathered
   to nothing on a smootherstep-cubed curve; its top is the top of the page
   and its right is the hero's own, so neither needs anything.

   Over it, one white layer, and it is the thinnest one the copy allows: a
   band that starts where the copy starts below 920px, a flat 0.75 shelf that
   ends where the glyphs end above it. See the annotated `.bg` / `.scrim`
   blocks in the stylesheet for the contrast table that prices it.
   ============================================ */

import React from 'react';
import { useHeroIntro } from '../../../animations';
import layout from '../../../styles/layout.module.css';
import styles from './HeroSection.module.css';

// Self-hosted backdrop — generated by `npm run generate:images` from the
// client's `iStock-2272021169` master on Cloudinary. That master is 2370x1264
// (1.875:1) and ships uncropped, so the large variant is 1920x1024 and the
// small one 960x512. The `-v2` basename is not cosmetic: `/images/**` answers
// `immutable`, so the retired photo's name could not be reused without
// stranding returning visitors on the old image for a year.
//
// `sizes="100vw"` overstates what the hero actually draws in the
// height-limited regime (~1037 CSS px at a 1920px viewport), which is the safe
// direction: it only ever picks a candidate at least as wide as the section,
// so the intrinsic width never becomes the binding term in the sizing rule
// and the frame never upscales.
const HERO_BG = '/images/hero-industries-v2.jpg';
const HERO_BG_SRCSET =
  '/images/hero-industries-v2-960.webp 960w, /images/hero-industries-v2-1920.webp 1920w';

const HeroSection = () => {
  const heroRef = useHeroIntro();

  return (
    <section className={styles.hero}>
      {/* Above the fold on this route — eager, and high priority so it wins
          the bandwidth race against the route chunk. `display: contents` on
          the <picture> keeps the absolutely positioned <img> laid out exactly
          as it would be as a direct child.

          A real <img> rather than a CSS background, and that is load-bearing
          rather than a preference: the element IS the drawn photograph, with
          no box fitted around it, which is what lets the stylesheet's edge
          feather be expressed in percentages of the image and land on its
          real edges. It also earns `fetchpriority="high"`, which a background
          cannot carry.

          No `useParallax` any more. Scrub parallax needs the photo drawn
          taller than its box so the travel never exposes an edge, and drawing
          the whole frame is the one thing that will not do — the overscan
          this section used to carry WAS the crop. The backdrop is static on
          purpose, the same call the home and expertise heroes make. */}
      <picture className={styles.bgPicture}>
        <source type="image/webp" srcSet={HERO_BG_SRCSET} sizes="100vw" />
        <img
          className={styles.bg}
          src={HERO_BG}
          alt=""
          aria-hidden="true"
          width="1920"
          height="1024"
          fetchpriority="high"
          decoding="async"
        />
      </picture>
      <div className={styles.scrim} aria-hidden="true" />

      <div ref={heroRef} className={`${layout.container} ${styles.inner}`}>
        <p className="eyebrow" data-hero>
          Who we serve
        </p>

        {/* Both clauses close on the word, not on a mark — see the home hero's
            "impact". The unconditional <br /> is what separates them, so the
            two lines hold at every width without the full stops. */}
        <h1 className={`display display--md ${styles.head}`} data-hero>
          Our expertise
          <br />
          <em className={`grad-text ${styles.accent}`}>Your industry</em>
        </h1>

        <p className={`lede ${styles.lede}`} data-hero>
          Our experience and professional perspective are adaptable to different
          sectors, organizational environments, and stages of growth.
        </p>
      </div>
    </section>
  );
};

export default HeroSection;
